package modelos;
// Generated 17-nov-2023 1:38:32 by Hibernate Tools 4.3.1



/**
 * ArtFactId generated by hbm2java
 */
public class ArtFactId  implements java.io.Serializable {


     private String referenciaart;
     private String numerofact;

    public ArtFactId() {
    }

    public ArtFactId(String referenciaart, String numerofact) {
       this.referenciaart = referenciaart;
       this.numerofact = numerofact;
    }
   
    public String getReferenciaart() {
        return this.referenciaart;
    }
    
    public void setReferenciaart(String referenciaart) {
        this.referenciaart = referenciaart;
    }
    public String getNumerofact() {
        return this.numerofact;
    }
    
    public void setNumerofact(String numerofact) {
        this.numerofact = numerofact;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ArtFactId) ) return false;
		 ArtFactId castOther = ( ArtFactId ) other; 
         
		 return ( (this.getReferenciaart()==castOther.getReferenciaart()) || ( this.getReferenciaart()!=null && castOther.getReferenciaart()!=null && this.getReferenciaart().equals(castOther.getReferenciaart()) ) )
 && ( (this.getNumerofact()==castOther.getNumerofact()) || ( this.getNumerofact()!=null && castOther.getNumerofact()!=null && this.getNumerofact().equals(castOther.getNumerofact()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getReferenciaart() == null ? 0 : this.getReferenciaart().hashCode() );
         result = 37 * result + ( getNumerofact() == null ? 0 : this.getNumerofact().hashCode() );
         return result;
   }   


}


