package modelos;
// Generated 17-nov-2023 1:38:32 by Hibernate Tools 4.3.1



/**
 * ArtFact generated by hbm2java
 */
public class ArtFact  implements java.io.Serializable {


     private ArtFactId id;
     private Facturas facturas;
     private Articulos articulos;
     private Integer cantidadart;

    public ArtFact() {
    }

	
    public ArtFact(ArtFactId id, Facturas facturas, Articulos articulos) {
        this.id = id;
        this.facturas = facturas;
        this.articulos = articulos;
    }
    public ArtFact(ArtFactId id, Facturas facturas, Articulos articulos, Integer cantidadart) {
       this.id = id;
       this.facturas = facturas;
       this.articulos = articulos;
       this.cantidadart = cantidadart;
    }
   
    public ArtFactId getId() {
        return this.id;
    }
    
    public void setId(ArtFactId id) {
        this.id = id;
    }
    public Facturas getFacturas() {
        return this.facturas;
    }
    
    public void setFacturas(Facturas facturas) {
        this.facturas = facturas;
    }
    public Articulos getArticulos() {
        return this.articulos;
    }
    
    public void setArticulos(Articulos articulos) {
        this.articulos = articulos;
    }
    public Integer getCantidadart() {
        return this.cantidadart;
    }
    
    public void setCantidadart(Integer cantidadart) {
        this.cantidadart = cantidadart;
    }




}


