package modelos;
// Generated 18-nov-2023 1:53:26 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

/**
 * Articulos generated by hbm2java
 */
public class Articulos implements java.io.Serializable {

    private String codarticulo;
    private Familias familias;
    private String nomarticulo;
    private BigDecimal precioarticulo;
    private Set facturases = new HashSet(0);

    public Articulos() {
    }

    public Articulos(String codarticulo) {
        this.codarticulo = codarticulo;
    }

    public Articulos(String codarticulo, Familias familias, String nomarticulo, BigDecimal precioarticulo, Set facturases) {
        this.codarticulo = codarticulo;
        this.familias = familias;
        this.nomarticulo = nomarticulo;
        this.precioarticulo = precioarticulo;
        this.facturases = facturases;
    }

    public Articulos(String codarticulo, Familias familias, String nomarticulo, BigDecimal precioarticulo) {
        this.codarticulo = codarticulo;
        this.familias = familias;
        this.nomarticulo = nomarticulo;
        this.precioarticulo = precioarticulo;
    }

    public String getCodarticulo() {
        return this.codarticulo;
    }

    public void setCodarticulo(String codarticulo) {
        this.codarticulo = codarticulo;
    }

    public Familias getFamilias() {
        return this.familias;
    }

    public void setFamilias(Familias familias) {
        this.familias = familias;
    }

    public String getNomarticulo() {
        return this.nomarticulo;
    }

    public void setNomarticulo(String nomarticulo) {
        this.nomarticulo = nomarticulo;
    }

    public BigDecimal getPrecioarticulo() {
        return this.precioarticulo;
    }

    public void setPrecioarticulo(BigDecimal precioarticulo) {
        this.precioarticulo = precioarticulo;
    }

    public Set getFacturases() {
        return this.facturases;
    }

    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }

}
