package modelos;
// Generated 15-nov-2023 2:06:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Articulos generated by hbm2java
 */
public class Articulos  implements java.io.Serializable {


     private String referart;
     private Familias familias;
     private String nomart;
     private Set facturases = new HashSet(0);

    public Articulos() {
    }

	
    public Articulos(String referart) {
        this.referart = referart;
    }
    public Articulos(String referart, Familias familias, String nomart, Set facturases) {
       this.referart = referart;
       this.familias = familias;
       this.nomart = nomart;
       this.facturases = facturases;
    }
   
    public String getReferart() {
        return this.referart;
    }
    
    public void setReferart(String referart) {
        this.referart = referart;
    }
    public Familias getFamilias() {
        return this.familias;
    }
    
    public void setFamilias(Familias familias) {
        this.familias = familias;
    }
    public String getNomart() {
        return this.nomart;
    }
    
    public void setNomart(String nomart) {
        this.nomart = nomart;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }




}


