package modelos;
// Generated 18-nov-2023 1:53:26 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Articulo generated by hbm2java
 */
public class Articulo implements java.io.Serializable {

    private String codArticulo;
    private Familia familia;
    private String nomArticulo;
    private BigDecimal precioArticulo;
    private Set listaFacturas = new HashSet(0);

    public Articulo() {
    }

    public Articulo(String codArticulo) {
        this.codArticulo = codArticulo;
    }

    public Articulo(String codArticulo, Familia familia, String nomArticulo, BigDecimal precioArticulo, Set listaFacturas) {
        this.codArticulo = codArticulo;
        this.familia = familia;
        this.nomArticulo = nomArticulo;
        this.precioArticulo = precioArticulo;
        this.listaFacturas = listaFacturas;
    }

    public Articulo(String codArticulo, Familia familia, String nomArticulo, BigDecimal precioArticulo) {
        this.codArticulo = codArticulo;
        this.familia = familia;
        this.nomArticulo = nomArticulo;
        this.precioArticulo = precioArticulo;
    }

    public String getCodArticulo() {
        return this.codArticulo;
    }

    public void setCodArticulo(String codArticulo) {
        this.codArticulo = codArticulo;
    }

    public Familia getFamilia() {
        return this.familia;
    }

    public void setFamilia(Familia familia) {
        this.familia = familia;
    }

    public String getNomArticulo() {
        return this.nomArticulo;
    }

    public void setNomArticulo(String nomArticulo) {
        this.nomArticulo = nomArticulo;
    }

    public BigDecimal getPrecioArticulo() {
        return this.precioArticulo;
    }

    public void setPrecioArticulo(BigDecimal precioArticulo) {
        this.precioArticulo = precioArticulo;
    }

    public Set getListaFacturas() {
        return this.listaFacturas;
    }

    public void setListaFacturas(Set listaFacturas) {
        this.listaFacturas = listaFacturas;
    }

    //Funciones creadas por mí
    //Función de añadir una factura al set de facturas de un artículo (artículos es el master, facturas el slave).
    public void addFactura(Factura factura){
        this.getListaFacturas().add(factura);    
    }
    
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + Objects.hashCode(this.codArticulo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Articulo other = (Articulo) obj;
        if (!Objects.equals(this.codArticulo, other.codArticulo)) {
            return false;
        }
        return true;
    }
}
