package modelos;
// Generated 18-nov-2023 1:53:26 by Hibernate Tools 4.3.1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Articulos generated by hbm2java
 */
public class Articulos implements java.io.Serializable {

    private String codarticulo;
    private Familias familias;
    private String nomarticulo;
    private BigDecimal precioarticulo;
    private Set facturases = new HashSet(0);

    public Articulos() {
    }

    public Articulos(String codarticulo) {
        this.codarticulo = codarticulo;
    }

    public Articulos(String codarticulo, Familias familias, String nomarticulo, BigDecimal precioarticulo, Set facturases) {
        this.codarticulo = codarticulo;
        this.familias = familias;
        this.nomarticulo = nomarticulo;
        this.precioarticulo = precioarticulo;
        this.facturases = facturases;
    }

    public Articulos(String codarticulo, Familias familias, String nomarticulo, BigDecimal precioarticulo) {
        this.codarticulo = codarticulo;
        this.familias = familias;
        this.nomarticulo = nomarticulo;
        this.precioarticulo = precioarticulo;
    }

    public String getCodarticulo() {
        return this.codarticulo;
    }

    public void setCodarticulo(String codarticulo) {
        this.codarticulo = codarticulo;
    }

    public Familias getFamilias() {
        return this.familias;
    }

    public void setFamilias(Familias familias) {
        this.familias = familias;
    }

    public String getNomarticulo() {
        return this.nomarticulo;
    }

    public void setNomarticulo(String nomarticulo) {
        this.nomarticulo = nomarticulo;
    }

    public BigDecimal getPrecioarticulo() {
        return this.precioarticulo;
    }

    public void setPrecioarticulo(BigDecimal precioarticulo) {
        this.precioarticulo = precioarticulo;
    }

    public Set getFacturases() {
        return this.facturases;
    }

    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }

    //Funciones creadas por mí
    //Función de añadir una factura al set de facturas de un artículo (artículos es el master, facturas el slave).
    public void addFacturas(Facturas facturas){
        this.getFacturases().add(facturas);    
    }
    
    
    
    
    
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 17 * hash + Objects.hashCode(this.codarticulo);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Articulos other = (Articulos) obj;
        if (!Objects.equals(this.codarticulo, other.codarticulo)) {
            return false;
        }
        return true;
    }
    
    

}
