package modelos;
// Generated 17-nov-2023 1:38:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private String dnicli;
     private String nombrecli;
     private String domiciliocli;
     private String telefonocli;
     private Set facturases = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(String dnicli) {
        this.dnicli = dnicli;
    }
    public Clientes(String dnicli, String nombrecli, String domiciliocli, String telefonocli, Set facturases) {
       this.dnicli = dnicli;
       this.nombrecli = nombrecli;
       this.domiciliocli = domiciliocli;
       this.telefonocli = telefonocli;
       this.facturases = facturases;
    }
   
    public String getDnicli() {
        return this.dnicli;
    }
    
    public void setDnicli(String dnicli) {
        this.dnicli = dnicli;
    }
    public String getNombrecli() {
        return this.nombrecli;
    }
    
    public void setNombrecli(String nombrecli) {
        this.nombrecli = nombrecli;
    }
    public String getDomiciliocli() {
        return this.domiciliocli;
    }
    
    public void setDomiciliocli(String domiciliocli) {
        this.domiciliocli = domiciliocli;
    }
    public String getTelefonocli() {
        return this.telefonocli;
    }
    
    public void setTelefonocli(String telefonocli) {
        this.telefonocli = telefonocli;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }




}


