package modelos;
// Generated 15-nov-2023 2:06:07 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Clientes generated by hbm2java
 */
public class Clientes  implements java.io.Serializable {


     private String dnicli;
     private String nomclien;
     private Set facturases = new HashSet(0);

    public Clientes() {
    }

	
    public Clientes(String dnicli) {
        this.dnicli = dnicli;
    }
    public Clientes(String dnicli, String nomclien, Set facturases) {
       this.dnicli = dnicli;
       this.nomclien = nomclien;
       this.facturases = facturases;
    }
   
    public String getDnicli() {
        return this.dnicli;
    }
    
    public void setDnicli(String dnicli) {
        this.dnicli = dnicli;
    }
    public String getNomclien() {
        return this.nomclien;
    }
    
    public void setNomclien(String nomclien) {
        this.nomclien = nomclien;
    }
    public Set getFacturases() {
        return this.facturases;
    }
    
    public void setFacturases(Set facturases) {
        this.facturases = facturases;
    }




}


