package modelos;
// Generated 18-nov-2023 1:53:26 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Cliente generated by hbm2java
 */
public class Cliente implements java.io.Serializable {

    private String codCliente;
    private String nomCliente;
    private String domicilioCli;
    private Set listaFacturas = new HashSet(0);

    public Cliente() {
    }

    public Cliente(String codCliente) {
        this.codCliente = codCliente;
    }

    public Cliente(String codCliente, String nomCliente, String domicilioCli, Set listaFacturas) {
        this.codCliente = codCliente;
        this.nomCliente = nomCliente;
        this.domicilioCli = domicilioCli;
        this.listaFacturas = listaFacturas;
    }

    public Cliente(String codCliente, String nomCliente, String domicilioCli) {
        this.codCliente = codCliente;
        this.nomCliente = nomCliente;
        this.domicilioCli = domicilioCli;
    }

    public String getCodCliente() {
        return this.codCliente;
    }

    public void setCodCliente(String codCliente) {
        this.codCliente = codCliente;
    }

    public String getNomCliente() {
        return this.nomCliente;
    }

    public void setNomCliente(String nomCliente) {
        this.nomCliente = nomCliente;
    }

    public String getDomicilioCli() {
        return this.domicilioCli;
    }

    public void setDomicilioCli(String domicilioCli) {
        this.domicilioCli = domicilioCli;
    }

    public Set getListaFacturas() {
        return this.listaFacturas;
    }

    public void setListaFacturas(Set listaFacturas) {
        this.listaFacturas = listaFacturas;
    }

    @Override
    public int hashCode() {
        int hash = 5;
        hash = 89 * hash + Objects.hashCode(this.codCliente);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Cliente other = (Cliente) obj;
        if (!Objects.equals(this.codCliente, other.codCliente)) {
            return false;
        }
        return true;
    }
}
