package modelos;
// Generated 18-nov-2023 1:53:26 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Facturas generated by hbm2java
 */
public class Facturas  implements java.io.Serializable {


     private BigDecimal numfactura;
     private Clientes clientes;
     private Date fechafactura;
     private Set articuloses = new HashSet(0);

    public Facturas() {
    }

	
    public Facturas(BigDecimal numfactura) {
        this.numfactura = numfactura;
    }
    public Facturas(BigDecimal numfactura, Clientes clientes, Date fechafactura, Set articuloses) {
       this.numfactura = numfactura;
       this.clientes = clientes;
       this.fechafactura = fechafactura;
       this.articuloses = articuloses;
    }
   
    public BigDecimal getNumfactura() {
        return this.numfactura;
    }
    
    public void setNumfactura(BigDecimal numfactura) {
        this.numfactura = numfactura;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Date getFechafactura() {
        return this.fechafactura;
    }
    
    public void setFechafactura(Date fechafactura) {
        this.fechafactura = fechafactura;
    }
    public Set getArticuloses() {
        return this.articuloses;
    }
    
    public void setArticuloses(Set articuloses) {
        this.articuloses = articuloses;
    }




}


