package modelos;
// Generated 17-nov-2023 1:38:32 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Facturas generated by hbm2java
 */
public class Facturas  implements java.io.Serializable {


     private String numerofact;
     private Clientes clientes;
     private Date fechafact;
     private String estadofact;
     private Set artFacts = new HashSet(0);

    public Facturas() {
    }

	
    public Facturas(String numerofact) {
        this.numerofact = numerofact;
    }
    public Facturas(String numerofact, Clientes clientes, Date fechafact, String estadofact, Set artFacts) {
       this.numerofact = numerofact;
       this.clientes = clientes;
       this.fechafact = fechafact;
       this.estadofact = estadofact;
       this.artFacts = artFacts;
    }
   
    public String getNumerofact() {
        return this.numerofact;
    }
    
    public void setNumerofact(String numerofact) {
        this.numerofact = numerofact;
    }
    public Clientes getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Clientes clientes) {
        this.clientes = clientes;
    }
    public Date getFechafact() {
        return this.fechafact;
    }
    
    public void setFechafact(Date fechafact) {
        this.fechafact = fechafact;
    }
    public String getEstadofact() {
        return this.estadofact;
    }
    
    public void setEstadofact(String estadofact) {
        this.estadofact = estadofact;
    }
    public Set getArtFacts() {
        return this.artFacts;
    }
    
    public void setArtFacts(Set artFacts) {
        this.artFacts = artFacts;
    }




}


