package modelos;
// Generated 17-nov-2023 1:38:32 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Familias generated by hbm2java
 */
public class Familias implements java.io.Serializable {

    private String codigofam;
    private String nombrefam;
    private String descripcionfam;
    private String categoriafam;
    private Set articuloses = new HashSet(0);

    public Familias() {
    }

    public Familias(String codigofam) {
        this.codigofam = codigofam;
    }

    public Familias(String codigofam, String nombrefam, String descripcionfam, String categoriafam, Set articuloses) {
        this.codigofam = codigofam;
        this.nombrefam = nombrefam;
        this.descripcionfam = descripcionfam;
        this.categoriafam = categoriafam;
        this.articuloses = articuloses;
    }

    public String getCodigofam() {
        return this.codigofam;
    }

    public void setCodigofam(String codigofam) {
        this.codigofam = codigofam;
    }

    public String getNombrefam() {
        return this.nombrefam;
    }

    public void setNombrefam(String nombrefam) {
        this.nombrefam = nombrefam;
    }

    public String getDescripcionfam() {
        return this.descripcionfam;
    }

    public void setDescripcionfam(String descripcionfam) {
        this.descripcionfam = descripcionfam;
    }

    public String getCategoriafam() {
        return this.categoriafam;
    }

    public void setCategoriafam(String categoriafam) {
        this.categoriafam = categoriafam;
    }

    public Set getArticuloses() {
        return this.articuloses;
    }

    public void setArticuloses(Set articuloses) {
        this.articuloses = articuloses;
    }

    //Creados por mí
    @Override
    public int hashCode() {
        int hash = 7;
        hash = 89 * hash + Objects.hashCode(this.codigofam);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Familias other = (Familias) obj;
        if (!Objects.equals(this.codigofam, other.codigofam)) {
            return false;
        }
        return true;
    }

}
