package modelos;
// Generated 18-nov-2023 1:53:26 by Hibernate Tools 4.3.1

import java.util.HashSet;
import java.util.Objects;
import java.util.Set;

/**
 * Familia generated by hbm2java
 */
public class Familia implements java.io.Serializable {

    private String codFamilia;
    private String nomFamilia;
    private String descFamilia;
    private Set listaArticulos = new HashSet(0);

    public Familia() {
    }

    public Familia(String codFamilia) {
        this.codFamilia = codFamilia;
    }

    public Familia(String codFamilia, String nomFamilia, String descFamilia, Set listaArticulos) {
        this.codFamilia = codFamilia;
        this.nomFamilia = nomFamilia;
        this.descFamilia = descFamilia;
        this.listaArticulos = listaArticulos;
    }

    //Constructor creado por mí
    public Familia(String codFamilia, String nomFamilia, String descFamilia) {
        this.codFamilia = codFamilia;
        this.nomFamilia = nomFamilia;
        this.descFamilia = descFamilia;
    }

    public String getCodFamilia() {
        return this.codFamilia;
    }

    public void setCodFamilia(String codFamilia) {
        this.codFamilia = codFamilia;
    }

    public String getNomFamilia() {
        return this.nomFamilia;
    }

    public void setNomFamilia(String nomFamilia) {
        this.nomFamilia = nomFamilia;
    }

    public String getDescFamilia() {
        return this.descFamilia;
    }

    public void setDescFamilia(String descFamilia) {
        this.descFamilia = descFamilia;
    }

    public Set getListaArticulos() {
        return this.listaArticulos;
    }

    public void setListaArticulos(Set listaArticulos) {
        this.listaArticulos = listaArticulos;
    }

    @Override
    public int hashCode() {
        int hash = 3;
        hash = 47 * hash + Objects.hashCode(this.codFamilia);
        return hash;
    }

    @Override
    public boolean equals(Object obj) {
        if (this == obj) {
            return true;
        }
        if (obj == null) {
            return false;
        }
        if (getClass() != obj.getClass()) {
            return false;
        }
        final Familia other = (Familia) obj;
        if (!Objects.equals(this.codFamilia, other.codFamilia)) {
            return false;
        }
        return true;
    }

}
